name: Test
on:
  push:
    branches-ignore:
      - development
jobs:
  install-cache-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.1
      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8.3.1
          run_install: false
      - name: Get PNPM store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - name: Setup PNPM cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Authenticate
        run: echo "@faruuko:registry = https://npm.pkg.github.com/ //npm.pkg.github.com:_authToken=${{ secrets.PACKAGE_OPERATIONS_ACCESS_TOKEN }}" > ~/.npmrc
      - name: Install dependencies
        run: npm install
      - name: Test
        run: pnpm test -- --coverage=true --coverageReporters=text
